### PR TITLE
Precisions on the certificate renewal logs

### PR DESCRIPTION
**Pull request by bflorat**

### CODE REVIEW

**Comment by bflorat** [comment]
I signed CLA

**Comment by ahmetb** [comment]
Thanks this looks good.
But I wanna make sure cert-manager still has this renewal event. Your screenshot in the issue didn't show that. If not, they should probably add it back.

**Comment by bflorat** [comment]
Not sure to understand. The command 
```
$ kubectl logs -n kube-system -l app=cert-manager -c cert-manager  | grep -i renew
```
gives me : 
```
I1011 09:34:41.167397       1 sync.go:206] Certificate default/dogs-com-tls scheduled for renewal in 1438 hours
I1011 09:35:41.173698       1 sync.go:206] Certificate default/dogs-com-tls scheduled for renewal in 1438 hours

```
the renewal is explicit, isn't it ?

**Comment by ahmetb** [comment]
@bflorat it used to be an Event as shown on the Certificate object.
I want to understand why the devs of cert-manager does not keep it that way.

**Comment by ahmetb** [comment]
We refactored that section and those events aren't there in newer versions so this is obsolete now. But thanks for the PR.

**Pull request closed without merging**
