### PR TITLE
Update 50-get-a-certificate.md

### PR DESCRIPTION
**Pull request by andrewmclagan**
Small gramatical errors

### CODE REVIEW

**Comment by ahmetb** [comment]
I meant to say "let's take a look at". 😄

**Comment by andrewmclagan** [comment]
haha ;-)

**Comment by andrewmclagan** [comment]
sorry i  cant sign the CLA at my workplace.

**Comment by ahmetb** [comment]
It's ok thanks for bringing this up. I'll fix myself.

**Pull request closed without merging**
