### PR TITLE
Update to acme v02

### PR DESCRIPTION
**Pull request by heysailor**
Solves #7

### CODE REVIEW

**Comment by heysailor** [comment]
Signed CLA

**Comment by ahmetb** [comment]
I see cert-manager is already mapping v1 to v2 here: https://github.com/jetstack/cert-manager/blob/8d1cad422ecbfd7e0c10180cf6c819a577393377/pkg/issuer/acme/util.go#L41-L46 so I'm not sure if this PR is necessary.

Paging @munnerz for help.

**Comment by ahmetb** [comment]
Maybe all we need to do is to bump the image in the helm chart?

**Comment by munnerz** [comment]
You will need to bump both the image version as well as the manifests used.

There were a number of breaking changes between 0.2 and 0.3: https://cert-manager.readthedocs.io/en/latest/admin/upgrading/upgrading-0.2-0.3.html

In general, this repo should, on each minor release:

* Ensure it is advising users to install the newest version of the Helm chart (e.g. `helm install --version v0.3.0`)

* Ensure the Issuer and Certificate manifests recommended are up to date (e.g. update v01 to v02 in this case)

For this particular release, I think just those two points will be sufficient. I'll make sure there is a doc like the one linked above between each minor release, so at least it is possible to see what's breaking.

**Comment by ahmetb** [comment]
Thanks @munnerz. I'll merge this and update the chart version!

**Pull request merged**
